/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 20 00:23:12 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option option0 = option_Builder0.get();
      option0.setArgs((-2989));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2989), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2147483642);
      option_Builder1.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder0.get();
      option0.setValueSeparator('d');
      option0.processValue("annot ad0value, dwst full.");
      assertEquals('d', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs((-2147483641));
      option_Builder1.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder0.get();
      option0.setValueSeparator('v');
      // Undeclared exception!
      try { 
        option0.processValue("Cannot add value, list ful.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('\\');
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("E");
      Option.Builder option_Builder1 = option_Builder0.required(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      option0.isValuesEmpty();
      assertEquals("Deprecated", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("y~(NX");
      option_Builder1.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue("");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setRequired(true);
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setOptionalArg(true);
      option0.hasOptionalArg();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.processValue("15_M.]]");
      option0.getValuesList();
      assertFalse(option0.hasLongOpt());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, "value");
      option0.setValueSeparator('4');
      char char0 = option0.getValueSeparator();
      assertEquals('4', char0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setValueSeparator('x');
      char char0 = option0.getValueSeparator();
      assertEquals('x', char0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option((String) null, "org.apache.commons.cli.TypeHandler");
      option0.getValue((String) null);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      String string0 = option0.getValue("");
      assertEquals((-1), option0.getArgs());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option option0 = new Option("WJO", "\"&e_@5o0nh0#", true, "WJO");
      option0.processValue("WJO");
      String string0 = option0.getValue(0);
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      option_Builder0.hasArg();
      Option option0 = option_Builder0.get();
      option0.processValue("");
      String string0 = option0.getValue(0);
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.processValue("15_M.]]");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("y~(NX");
      option_Builder1.since("y~(NX");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since("");
      Option.Builder option_Builder1 = option_Builder0.longOpt("nxGq05xkc+}+N7K0b]");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      option0.getOpt();
      assertEquals("Deprecated", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option("3hRd2", "3hRd2");
      String string0 = option0.getLongOpt();
      assertNull(string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option((String) null, " :: ");
      assertFalse(option0.hasLongOpt());
      
      option0.setLongOpt("");
      option0.getLongOpt();
      assertFalse(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setLongOpt("");
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      String string0 = option0.getDescription();
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      String string0 = option0.getDescription();
      assertEquals("Deprecated", option0.getLongOpt());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(0);
      option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      int int0 = option0.getArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      int int0 = option0.getArgs();
      assertEquals(1, int0);
      assertEquals("", option0.getDescription());
      assertEquals("Deprecated", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      option0.setArgName("[ ");
      option0.getArgName();
      assertEquals("Deprecated", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Rqk!L0%Cek`f3+}");
      option0.setArgName("");
      option0.getArgName();
      assertEquals("Rqk!L0%Cek`f3+}", option0.getDescription());
      assertEquals("Deprecated", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option("WJO", "\"&e_@5o0nh0#", true, "WJO");
      boolean boolean0 = option0.acceptsArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = new Option("dfS", "dfS");
      // Undeclared exception!
      try { 
        option0.setType((Object) "");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = new Option((String) null, " :: ");
      option0.setArgs(1751);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.processValue("15_M.]]");
      try { 
        option0.getValue((-2));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      String string0 = "\\u";
      Option option0 = null;
      try {
        option0 = new Option("", false, string0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option(" :: ", "", false, " :: ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option(":FcWb0oC", ":FcWb0oC");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ':'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.isDeprecated();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option("H", "H");
      boolean boolean0 = option0.hasValueSeparator();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      option0.setValueSeparator(':');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals(':', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      boolean boolean0 = option0.hasArgs();
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("value");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
      assertTrue(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.hasArg();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option((String) null, "Qq6PYBr8}-h'JIH1W");
      boolean boolean0 = option0.hasArg();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option((String) null, "Qq6PYBr8}-h'JIH1W");
      option0.getValue();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option option0 = new Option("0", "DG*> lp7zWlR+DT");
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertEquals("DG*> lp7zWlR+DT", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.getValueSeparator();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.hasOptionalArg();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option option0 = new Option("C5op3q", true, "T0E\"");
      Class<String> class0 = String.class;
      option0.setType(class0);
      assertFalse(option0.hasLongOpt());
      assertEquals("T0E\"", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("E");
      Option.Builder option_Builder1 = option_Builder0.option("E");
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      String string0 = option0.toString();
      assertEquals("[ Option Deprecated Deprecated [ARG] :: Deprecated :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder0.longOpt("org.apache.commons.cli.Converter");
      Option option0 = option_Builder0.get();
      String string0 = option0.toString();
      assertEquals((-1), option0.getArgs());
      assertEquals("[ Option null org.apache.commons.cli.Converter Deprecated :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      String string0 = option0.toString();
      assertEquals((-1), option0.getArgs());
      assertEquals("[ Option null :: value :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      Option.Builder option_Builder1 = option_Builder0.longOpt("y~(NX");
      Option.Builder option_Builder2 = option_Builder1.deprecated();
      Option option0 = option_Builder2.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'W''y~(NX': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      String string0 = option0.toDeprecatedString();
      assertFalse(option0.hasLongOpt());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("@");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      option0.processValue("@");
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("@");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.requiresArg();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option("C5op3q", true, "T0E\"");
      option0.setValueSeparator('p');
      option0.processValue("\r=cHB%+p7Yur,");
      assertEquals('p', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      // Undeclared exception!
      try { 
        option0.processValue("lvq");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      Option option0 = option_Builder1.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'W': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option option0 = new Option("7pZUN", "7pZUN");
      assertFalse(option0.hasLongOpt());
      
      option0.setLongOpt("7pZUN");
      boolean boolean0 = option0.hasLongOpt();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      boolean boolean0 = option0.hasLongOpt();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("@");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.setArgs(68);
      option0.toString();
      assertEquals(68, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "");
      option0.setArgName("[ ");
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Rqk!L0%Cek`f3+}");
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertEquals("Deprecated", option0.getLongOpt());
      assertFalse(boolean0);
      assertEquals("Rqk!L0%Cek`f3+}", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("C5op3q", true, "T0E\"");
      String[] stringArray0 = option0.getValues();
      assertFalse(option0.hasLongOpt());
      assertEquals("T0E\"", option0.getDescription());
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      assertTrue(option0.hasArg());
      
      option0.processValue("15_M.]]");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("@");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      option0.processValue("@");
      option0.getValue("@");
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.getValue(68);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option("C5op3q", true, "T0E\"");
      option0.processValue("\r=cHB%+p7Yur,");
      try { 
        option0.getValue(3071);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 3071, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue("");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      Option option1 = (Option)option0.clone();
      boolean boolean0 = option0.equals(option1);
      assertEquals(1, option1.getArgs());
      assertNotSame(option1, option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      Option option1 = new Option("converterMap", false, "converterMap");
      boolean boolean0 = option0.equals(option1);
      assertEquals((-1), option1.getArgs());
      assertFalse(option1.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option((String) null, "NO_ARGS_ALLOWED");
      Object object0 = new Object();
      boolean boolean0 = option0.equals(object0);
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      boolean boolean0 = option0.equals(option0);
      assertTrue(boolean0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      Option option1 = new Option((String) null, "0E", false, "0E");
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.processValue("0E");
      // Undeclared exception!
      try { 
        option0.processValue("0E");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("W");
      option_Builder0.hasArg();
      Option option0 = option_Builder0.get();
      assertEquals(1, option0.getArgs());
      
      option0.processValue("");
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option option0 = new Option((String) null, "NO_ARGS_ALLOWED");
      option0.setOptionalArg(true);
      option0.setArgs((-1020));
      option0.processValue("");
      assertEquals((-1020), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArg(true);
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option((String) null, true, "5?HO");
      option0.setLongOpt("");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      option0.getOpt();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getType();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.addValue("annot ad0value, dwst full.");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.getLongOpt();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.hashCode();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder0.get();
      option0.isRequired();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("y~(NX");
      Option option0 = option_Builder1.get();
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option option0 = option_Builder0.get();
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.clearValues();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.acceptsArg();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option option0 = new Option((String) null, "value");
      option0.setDescription("");
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      int int0 = option0.getId();
      assertEquals(68, int0);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertNotNull(converter1);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option option0 = new Option("C5op3q", true, "T0E\"");
      option0.getValuesList();
      assertFalse(option0.hasLongOpt());
      assertEquals("T0E\"", option0.getDescription());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option option0 = new Option("0E", true, "0E");
      option0.setOptionalArg(true);
      option0.setArgs(0);
      assertTrue(option0.hasOptionalArg());
      
      option0.processValue("0E");
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, "Deprecated");
      option0.getArgName();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Class<String> class0 = String.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option.Builder option_Builder2 = option_Builder0.optionalArg(true);
      assertSame(option_Builder2, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option.Builder option_Builder1 = option_Builder0.desc("EEE MMM dd HH:mm:ss zzz yyyy");
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2147483642);
      option_Builder1.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
      assertEquals(2147483642, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isDeprecated();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Option option0 = new Option("7pZUN", "7pZUN");
      Option.Builder option_Builder0 = Option.builder();
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      option_Builder0.converter(converter0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required();
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option.Builder option_Builder1 = option_Builder0.argName("[ ");
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      option_Builder1.hasArg(true);
      option_Builder0.longOpt("1|)Zp{x)(-E9Rj3V");
      Option option0 = option_Builder1.get();
      assertTrue(option0.hasArg());
      
      option0.processValue("annot ad0value, dwst full.");
      assertEquals('=', option0.getValueSeparator());
      assertTrue(option0.hasValueSeparator());
  }
}
