/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 20 00:44:14 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.StringWriter;
import java.nio.BufferOverflowException;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterHelpAppendable_ESTest extends FilterHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(7);
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) charBuffer0, 1, 1);
      assertEquals(3, TextHelpAppendable.DEFAULT_INDENT);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", Integer.MAX_VALUE, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter(0);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0, 7, 479);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("org.apache.commons.cli.help.FilterHelpAppendable");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockFileWriter0);
      mockFileWriter0.close();
      try { 
        textHelpAppendable0.append((CharSequence) "org.apache.commons.cli.help.FilterHelpAppendable", 3, 7);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      char[] charArray0 = new char[9];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "918V+?9f'=jeIp");
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "\u0000");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('b');
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('7');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(7);
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) charBuffer0);
      assertEquals(1, textHelpAppendable1.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append('Z');
      assertSame(filterHelpAppendable0, textHelpAppendable0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "n?F2k0Jm@q!n2", Integer.MAX_VALUE, 0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }
}
