/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Mar 20 00:45:33 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\PARMVE~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Parmveer Randhawa\\Documents\\Courses\\EECS4313-Software Test\\Assignment\\Assignment_2\\commons-cli"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Parmveer Randhawa"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Parmveer Randhawa"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.Converter",
      "org.apache.commons.io.file.AccumulatorPathVisitor$1",
      "org.junitpioneer.jupiter.cartesian.CartesianArgumentsProvider",
      "org.junitpioneer.jupiter.CartesianAnnotationConsumer",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$EmptyEnumeration",
      "org.junitpioneer.jupiter.cartesian.CartesianParameterArgumentsProvider",
      "net.bytebuddy.description.NamedElement",
      "org.apache.commons.cli.TypeHandler",
      "org.junitpioneer.jupiter.params.RangeSourceArgumentsProvider"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.ParseException",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.cli.Option",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.PathEqualsFileFilter",
      "org.apache.commons.io.file.AccumulatorPathVisitor$1",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.junitpioneer.jupiter.params.RangeSourceArgumentsProvider",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.UrlEncoderStringLookup",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.json.JsonInlineArgumentsProvider",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.text.lookup.ConstantStringLookup",
      "org.mockito.internal.creation.bytebuddy.StackWalkerChecker",
      "org.apache.commons.text.lookup.XmlEncoderStringLookup",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.text.lookup.AbstractPathFencedLookup",
      "org.apache.commons.text.lookup.PathFence",
      "org.apache.commons.text.lookup.PathFence$Builder",
      "org.apache.commons.text.lookup.PropertiesStringLookup",
      "org.apache.commons.io.file.DeletingPathVisitor",
      "net.bytebuddy.description.NamedElement",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "org.apache.commons.text.lookup.DateStringLookup",
      "org.apache.commons.text.lookup.JavaPlatformStringLookup",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.text.similarity.JaccardDistance",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.junitpioneer.jupiter.cartesian.CartesianValueArgumentsProvider",
      "org.apache.commons.io.filefilter.CanExecuteFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.io.serialization.FullClassNameMatcher",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$EmptyEnumeration",
      "org.apache.commons.text.lookup.DnsStringLookup",
      "org.apache.commons.text.lookup.XmlStringLookup",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler",
      "org.hsqldb.jdbc.JDBCDriver$1",
      "org.apache.commons.text.similarity.LevenshteinResults",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.text.lookup.UrlStringLookup",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "org.apache.commons.text.StrLookup",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.text.lookup.FileStringLookup"
    );
  }
}
