/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 20 15:53:49 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.time.chrono.MinguoEra;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.io.filefilter.IOFileFilter;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject("-e-~50");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("args");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption("WpeDWlHY");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[8];
      Object[] objectArray1 = commandLine0.getParsedOptionValues((OptionGroup) null, objectArray0);
      assertEquals(8, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = IOFileFilter.EMPTY_STRING_ARRAY;
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Object[]) stringArray0);
      assertSame(stringArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[0];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues((OptionGroup) null, supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[6];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues((Option) null, integerArray0);
      assertEquals(6, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      LinkedList<Integer>[] linkedListArray0 = (LinkedList<Integer>[]) Array.newInstance(LinkedList.class, 0);
      LinkedList<Integer>[] linkedListArray1 = commandLine0.getParsedOptionValues(option0, linkedListArray0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[8];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertSame(optionArray1, optionArray0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[0];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertSame(optionArray1, optionArray0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("<D(r.Ft%@*xM^Tm", (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = new Object[0];
      Object[] objectArray1 = commandLine0.getParsedOptionValues((String) null, objectArray0);
      assertEquals(0, objectArray1.length);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues("", supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = new String[0];
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      String[] stringArray1 = commandLine0.getParsedOptionValues("", supplier0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues('N', (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues('&', integerArray0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<MinguoEra[]> supplier0 = (Supplier<MinguoEra[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      MinguoEra[] minguoEraArray0 = commandLine0.getParsedOptionValues(';', supplier0);
      assertNull(minguoEraArray0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = new Option[0];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues('G', supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option((String) null, true, "g");
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("oY");
      Option option1 = commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
      assertFalse(option1.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = commandLine0.getParsedOptionValue((Option) null, (Option) null);
      assertNull(option0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Supplier<LinkedList<String>> supplier0 = (Supplier<LinkedList<String>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(supplier0).get();
      LinkedList<String> linkedList1 = commandLine0.getParsedOptionValue("iZ3>exE^", supplier0);
      assertSame(linkedList0, linkedList1);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Object> linkedList0 = commandLine0.getParsedOptionValue((String) null, (LinkedList<Object>) null);
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(117);
      String string0 = commandLine0.getParsedOptionValue('y', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue('I', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("options", true, (String) null);
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[2];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0, 0);
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("pathCounters", "pathCounters");
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("runtime");
      String string0 = commandLine0.getOptionValue((Option) null, (Supplier<String>) textStringBuilder0);
      assertEquals("runtime", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("DIGITS", "M5stAsB");
      String string0 = commandLine0.getOptionValue(option0, " since ");
      assertEquals(" since ", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((Option) null, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue(", length=", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[8];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue("", (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue("Sensitive", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("Cannot add value, list full.", "");
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('+', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[6];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue('U', (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('Z', "3NQR@4n$]i7\"|K8\"");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('X', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("oN", "oN");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fotth$U0l3", false, "3361)E(_^5%");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount("fotth$U0l3");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addArg("k;_j ttjyiM@6wl&");
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      commandLine_Builder0.addArg("WpeDWlHY");
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("WpeDWlHY"));
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, true, "12)\"$+5=`ka_<");
      Option.Builder option_Builder0 = Option.builder((String) null);
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((Option) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue("args", (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('(', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("fotth$U0l3", false, "3361)E(_^5%");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((Option) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      MinguoEra[] minguoEraArray0 = new MinguoEra[6];
      Supplier<MinguoEra[]> supplier0 = (Supplier<MinguoEra[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(minguoEraArray0).when(supplier0).get();
      MinguoEra[] minguoEraArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertEquals(6, minguoEraArray1.length);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("$6", "$6");
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Supplier<Class<Option>> supplier0 = (Supplier<Class<Option>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Class<Option> class0 = commandLine0.getParsedOptionValue(optionGroup0, supplier0);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue((Option) null, supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = null;
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("name", "name", false, "name");
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("z");
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("z", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((String) null);
      String string0 = commandLine0.getOptionValue((Option) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      Option[] optionArray0 = commandLine0.getParsedOptionValues(option0, (Option[]) null);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((OptionGroup) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("DIGITS", "M5stAsB");
      LinkedList<LinkedList>[] linkedListArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("mDziKs_7nm*");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues("");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, "");
      Option option1 = commandLine0.getParsedOptionValue(option0);
      assertNull(option1);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue("", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((Option) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue((Option) null, "G?PN21#3");
      assertEquals("G?PN21#3", string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<LinkedList> linkedList0 = commandLine0.getParsedOptionValue("");
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("o");
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("ars");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = option_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("o");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("o");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option.Builder option_Builder0 = Option.builder("ars");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = option_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Option[] optionArray0 = commandLine0.getParsedOptionValues(optionGroup0);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Option option1 = commandLine0.getParsedOptionValue(optionGroup0, option0);
      assertSame(option0, option1);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[7];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addOption(option0);
      assertEquals((-2), Option.UNLIMITED_VALUES);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("z");
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("WpeDWlHY", "epphc0{B&,D3?");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues("WpeDWlHY");
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      commandLine0.getParsedOptionValue(optionGroup0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue('e', supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("7 g~u){b1#UeMHX", "FX=pcMK+[jHc6<A");
      assertEquals("FX=pcMK+[jHc6<A", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(0, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[5];
      Option[] optionArray1 = commandLine0.getParsedOptionValues('p', optionArray0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "z");
      assertEquals("z", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption('e');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties((String) null);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[1];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues('O', supplier0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject('/');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getParsedOptionValues(':');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues('*');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('Q');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      char[] charArray0 = new char[1];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0, 0);
      String string0 = commandLine0.getOptionValue('Q', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      MinguoEra minguoEra0 = MinguoEra.ROC;
      MinguoEra minguoEra1 = commandLine0.getParsedOptionValue('p', minguoEra0);
      assertSame(minguoEra1, minguoEra0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('u', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue("org.apache.commons.io.filefilter.DelegateFileFilter", supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = new Object[6];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues((String) null, supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount((Option) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue("org.apache.commons.cli.CommandLine", "4fRO");
      assertEquals("4fRO", string0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue('^');
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<String>[] linkedListArray0 = (LinkedList<String>[]) Array.newInstance(LinkedList.class, 5);
      LinkedList<String>[] linkedListArray1 = commandLine0.getParsedOptionValues("", linkedListArray0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('u');
      assertNull(string0);
  }
}
